{% set name = "iwopy" %}
{% set version = "0.3.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/iwopy/archive/v{{ version }}.tar.gz
  sha256: 30181944369d7193afd47a81a45550acaeaa50931ac4bf0114e0dedc08c381e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - iwopy
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pymoo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/iwopy
  summary: Fraunhofer IWES optimization tools in Python
  description: |
    The iwopy package is a meta package that provides interfaces to
    other open-source Python optimization packages out there. It can
    thus be understood as an attempt to provide the best of all worlds
    when it comes to solving optimization problems with Python. All 
    the credit for implementing the invoked optimizers goes to the
    original package providers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
