{% set name = "iwopy" %}
{% set version = "0.3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/iwopy/archive/v{{ version }}.tar.gz
  sha256: cea8d8092d1f47b1ad839ec60e4de8f72b32c8134351d8b9d20d7ef499e8d69b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - matplotlib-base
    - numpy
    - scipy
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - iwopy
  requires:
    - pip
    - pytest
    - pymoo
    - pygmo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/iwopy
  summary: Fraunhofer IWES optimization tools in Python
  description: |
    The iwopy package is a meta package that provides interfaces to
    other open-source Python optimization packages out there. It can
    thus be understood as an attempt to provide the best of all worlds
    when it comes to solving optimization problems with Python. All 
    the credit for implementing the invoked optimizers goes to the
    original package providers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
